### ISSUE TITLE
Add `+strict-align` to `.cargo/config`

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/rust-raspi3-tutorial#12]
Prevents issues like #10

**Comment by andre-richter** [comment]
@digitalstreamio this is now upstream and should land in the nightly toolchain sometime soon.

Prevents #10

**Comment by digitalstreamio** [comment]
Awesome. I was just hit by this again while trying to copy data from device memory used by my sd card handling code to my app level state. 

I can certainly appreciate the generated code no longer halting the cpu ;).

Out of curiosity though, are there any downsides to turning this on?

**Comment by digitalstreamio** [comment]
Also, I will gladly give it a spin in a day or two once nightly picks it up. Cheers!

**Comment by andre-richter** [comment]
With the option turned on, the compiler circumvents miss-aligned accesses by generating code in a way that it doesn't fail, eg using two 32bit accesses instead of one 64bit access if your operate on an address where modulo 8 != 0. This will cause your code to function, but probably it won't be the fastest possible code.

So you gain  that your code doesn't crash and  trade It for potentially slight performance hits.
